on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files
        run: ls
      # actions are resualble piece of code by github to perfrom commo tasks like clone repo set up nodes 
              